"""Published API contracts; source revisions are recorded in tests/parity-audit.json."""

TASK_PATH = "/openai/tasks"

ENDPOINTS = {
    "gpt_image_generate_image": {
        "method": "POST",
        "path": "/openai/images/generations",
        "operation": "generate",
        "schema": {
            "type": "object",
            "required": ["prompt", "model"],
            "properties": {
                "prompt": {"type": "string"},
                "background": {"enum": ["transparent", "opaque", "auto"], "type": "string"},
                "model": {
                    "enum": [
                        "dall-e-2",
                        "dall-e-3",
                        "gpt-image-1",
                        "gpt-image-1.5",
                        "gpt-image-2",
                        "gpt-image-2.5-flare",
                        "gpt-image-2.5-flare:official",
                        "gpt-image-2.5-sunburst",
                        "gpt-image-2.5-sunburst:official",
                        "gpt-image-2:reverse",
                        "gpt-image-2:official",
                        "nano-banana",
                        "nano-banana-2-lite",
                        "nano-banana-2",
                        "nano-banana-pro",
                    ],
                    "type": "string",
                },
                "moderation": {"enum": ["low", "auto"], "type": "string"},
                "n": {"type": "integer", "minimum": 1, "maximum": 10},
                "output_compression": {"type": "integer", "minimum": 0, "maximum": 100},
                "output_format": {"enum": ["png", "jpeg", "webp"], "type": "string"},
                "partial_images": {"type": "integer", "minimum": 0, "maximum": 3},
                "size": {"type": ["string", "null"], "pattern": "^(auto|\\d+x\\d+)$"},
                "quality": {
                    "enum": ["auto", "high", "medium", "low", "hd", "standard"],
                    "type": "string",
                },
                "response_format": {"enum": ["url", "b64_json"], "type": ["string", "null"]},
                "style": {"enum": ["vivid", "natural"], "type": "string"},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "prompt": {"type": "string"},
            "background": {"enum": ["transparent", "opaque", "auto"], "type": "string"},
            "model": {
                "enum": [
                    "dall-e-2",
                    "dall-e-3",
                    "gpt-image-1",
                    "gpt-image-1.5",
                    "gpt-image-2",
                    "gpt-image-2.5-flare",
                    "gpt-image-2.5-flare:official",
                    "gpt-image-2.5-sunburst",
                    "gpt-image-2.5-sunburst:official",
                    "gpt-image-2:reverse",
                    "gpt-image-2:official",
                    "nano-banana",
                    "nano-banana-2-lite",
                    "nano-banana-2",
                    "nano-banana-pro",
                ],
                "type": "string",
            },
            "moderation": {"enum": ["low", "auto"], "type": "string"},
            "n": {"type": "integer", "minimum": 1, "maximum": 10},
            "output_compression": {"type": "integer", "minimum": 0, "maximum": 100},
            "output_format": {"enum": ["png", "jpeg", "webp"], "type": "string"},
            "partial_images": {"type": "integer", "minimum": 0, "maximum": 3},
            "size": {"type": ["string", "null"], "pattern": "^(auto|\\d+x\\d+)$"},
            "quality": {
                "enum": ["auto", "high", "medium", "low", "hd", "standard"],
                "type": "string",
            },
            "response_format": {"enum": ["url", "b64_json"], "type": ["string", "null"]},
            "style": {"enum": ["vivid", "natural"], "type": "string"},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"model": "gpt-image-2", "size": "1024x1024", "quality": "auto", "n": 1},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": True,
    },
    "gpt_image_edit_image": {
        "method": "POST",
        "path": "/openai/images/edits",
        "operation": "edit",
        "schema": {
            "type": "object",
            "required": ["image", "prompt"],
            "properties": {
                "image": {
                    "oneOf": [
                        {"type": "string", "format": "uri"},
                        {
                            "type": "array",
                            "items": {"type": "string", "format": "uri"},
                            "maxItems": 16,
                        },
                    ]
                },
                "prompt": {"type": "string"},
                "model": {
                    "enum": [
                        "dall-e-2",
                        "dall-e-3",
                        "gpt-image-1",
                        "gpt-image-1.5",
                        "gpt-image-2",
                        "gpt-image-2.5-flare",
                        "gpt-image-2.5-flare:official",
                        "gpt-image-2.5-sunburst",
                        "gpt-image-2.5-sunburst:official",
                        "gpt-image-2:reverse",
                        "gpt-image-2:official",
                        "nano-banana",
                        "nano-banana-2-lite",
                        "nano-banana-2",
                        "nano-banana-pro",
                    ],
                    "type": "string",
                },
                "n": {"type": "integer", "minimum": 1, "maximum": 10},
                "background": {"enum": ["transparent", "opaque", "auto"], "type": "string"},
                "input_fidelity": {"enum": ["high", "low"], "type": "string"},
                "output_format": {"enum": ["png", "jpeg", "webp"], "type": "string"},
                "output_compression": {"type": "integer", "minimum": 0, "maximum": 100},
                "quality": {
                    "enum": ["auto", "high", "medium", "low", "standard"],
                    "type": "string",
                },
                "size": {"type": ["string", "null"], "pattern": "^(auto|\\d+x\\d+)$"},
                "response_format": {"enum": ["url", "b64_json"], "type": ["string", "null"]},
                "callback_url": {"type": "string"},
                "async": {"type": "boolean"},
            },
        },
        "properties": {
            "image": {
                "oneOf": [
                    {"type": "string", "format": "uri"},
                    {"type": "array", "items": {"type": "string", "format": "uri"}, "maxItems": 16},
                ]
            },
            "prompt": {"type": "string"},
            "model": {
                "enum": [
                    "dall-e-2",
                    "dall-e-3",
                    "gpt-image-1",
                    "gpt-image-1.5",
                    "gpt-image-2",
                    "gpt-image-2.5-flare",
                    "gpt-image-2.5-flare:official",
                    "gpt-image-2.5-sunburst",
                    "gpt-image-2.5-sunburst:official",
                    "gpt-image-2:reverse",
                    "gpt-image-2:official",
                    "nano-banana",
                    "nano-banana-2-lite",
                    "nano-banana-2",
                    "nano-banana-pro",
                ],
                "type": "string",
            },
            "n": {"type": "integer", "minimum": 1, "maximum": 10},
            "background": {"enum": ["transparent", "opaque", "auto"], "type": "string"},
            "input_fidelity": {"enum": ["high", "low"], "type": "string"},
            "output_format": {"enum": ["png", "jpeg", "webp"], "type": "string"},
            "output_compression": {"type": "integer", "minimum": 0, "maximum": 100},
            "quality": {"enum": ["auto", "high", "medium", "low", "standard"], "type": "string"},
            "size": {"type": ["string", "null"], "pattern": "^(auto|\\d+x\\d+)$"},
            "response_format": {"enum": ["url", "b64_json"], "type": ["string", "null"]},
            "callback_url": {"type": "string"},
            "async": {"type": "boolean"},
        },
        "parameters": [],
        "defaults": {"model": "gpt-image-2", "size": "1024x1024", "quality": "auto", "n": 1},
        "fixed": {},
        "allow_empty": [],
        "query_actions": [],
        "media_response": True,
    },
    "gpt_image_list_tasks": {
        "method": "POST",
        "path": "/openai/tasks",
        "operation": "request",
        "schema": {
            "type": "object",
            "properties": {
                "action": {"type": "string", "enum": ["retrieve", "retrieve_batch"]},
                "id": {"type": "string"},
                "trace_id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "trace_ids": {"type": "array", "items": {"type": "string"}},
                "application_id": {"type": "string"},
                "user_id": {"type": "string"},
                "type": {
                    "type": "string",
                    "enum": ["images", "images_generations", "images_edits"],
                },
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "created_at_min": {"type": "number"},
                "created_at_max": {"type": "number"},
                "count_mode": {"type": "string", "enum": ["none", "exact"]},
            },
        },
        "properties": {
            "action": {"type": "string", "enum": ["retrieve", "retrieve_batch"]},
            "id": {"type": "string"},
            "trace_id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "trace_ids": {"type": "array", "items": {"type": "string"}},
            "application_id": {"type": "string"},
            "user_id": {"type": "string"},
            "type": {"type": "string", "enum": ["images", "images_generations", "images_edits"]},
            "offset": {"type": "integer"},
            "limit": {"type": "integer"},
            "created_at_min": {"type": "number"},
            "created_at_max": {"type": "number"},
            "count_mode": {"type": "string", "enum": ["none", "exact"]},
        },
        "parameters": [],
        "defaults": {"action": "retrieve_batch"},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "gpt_image_task_retrieve": {
        "method": "POST",
        "path": "/openai/tasks",
        "operation": "task",
        "schema": {
            "type": "object",
            "properties": {
                "action": {"type": "string", "enum": ["retrieve", "retrieve_batch"]},
                "id": {"type": "string"},
                "trace_id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}},
                "trace_ids": {"type": "array", "items": {"type": "string"}},
                "application_id": {"type": "string"},
                "user_id": {"type": "string"},
                "type": {
                    "type": "string",
                    "enum": ["images", "images_generations", "images_edits"],
                },
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "created_at_min": {"type": "number"},
                "created_at_max": {"type": "number"},
                "count_mode": {"type": "string", "enum": ["none", "exact"]},
            },
        },
        "properties": {
            "action": {"type": "string", "enum": ["retrieve", "retrieve_batch"]},
            "id": {"type": "string"},
            "trace_id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}},
            "trace_ids": {"type": "array", "items": {"type": "string"}},
            "application_id": {"type": "string"},
            "user_id": {"type": "string"},
            "type": {"type": "string", "enum": ["images", "images_generations", "images_edits"]},
            "offset": {"type": "integer"},
            "limit": {"type": "integer"},
            "created_at_min": {"type": "number"},
            "created_at_max": {"type": "number"},
            "count_mode": {"type": "string", "enum": ["none", "exact"]},
        },
        "parameters": [],
        "defaults": {"wait_seconds": 0},
        "fixed": {},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
    "gpt_image_tasks_retrieve_batch": {
        "method": "POST",
        "path": "/openai/tasks",
        "operation": "batch",
        "schema": {
            "type": "object",
            "properties": {
                "action": {"type": "string", "enum": ["retrieve", "retrieve_batch"]},
                "id": {"type": "string"},
                "trace_id": {"type": "string"},
                "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "trace_ids": {"type": "array", "items": {"type": "string"}},
                "application_id": {"type": "string"},
                "user_id": {"type": "string"},
                "type": {
                    "type": "string",
                    "enum": ["images", "images_generations", "images_edits"],
                },
                "offset": {"type": "integer"},
                "limit": {"type": "integer"},
                "created_at_min": {"type": "number"},
                "created_at_max": {"type": "number"},
                "count_mode": {"type": "string", "enum": ["none", "exact"]},
            },
            "required": ["action"],
        },
        "properties": {
            "action": {"type": "string", "enum": ["retrieve", "retrieve_batch"]},
            "id": {"type": "string"},
            "trace_id": {"type": "string"},
            "ids": {"type": "array", "items": {"type": "string"}, "minItems": 1},
            "trace_ids": {"type": "array", "items": {"type": "string"}},
            "application_id": {"type": "string"},
            "user_id": {"type": "string"},
            "type": {"type": "string", "enum": ["images", "images_generations", "images_edits"]},
            "offset": {"type": "integer"},
            "limit": {"type": "integer"},
            "created_at_min": {"type": "number"},
            "created_at_max": {"type": "number"},
            "count_mode": {"type": "string", "enum": ["none", "exact"]},
        },
        "parameters": [],
        "defaults": {},
        "fixed": {"action": "retrieve_batch"},
        "allow_empty": [],
        "query_actions": ["retrieve", "retrieve_batch", "list", "presets"],
        "media_response": False,
    },
}
